package model;

import java.math.BigDecimal;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 26 16:15:54 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for OpportunitiesVO1.
     * @return OpportunitiesVO1
     */
    public ViewObjectImpl getOpportunitiesVO1() {
        return (ViewObjectImpl) findViewObject("OpportunitiesVO1");
    }

    /**
     * Container's getter for ContactOppurtunityVO1.
     * @return ContactOppurtunityVO1
     */
    public ViewObjectImpl getContactOppurtunityVO1() {
        return (ViewObjectImpl) findViewObject("ContactOppurtunityVO1");
    }

    /**
     * Container's getter for ContactsVO1.
     * @return ContactsVO1
     */
    public ViewObjectImpl getContactsVO1() {
        return (ViewObjectImpl) findViewObject("ContactsVO1");
    }

    /**
     * Container's getter for ContinvOpportunitiesFkLink1.
     * @return ContinvOpportunitiesFkLink1
     */
    public ViewLinkImpl getContinvOpportunitiesFkLink1() {
        return (ViewLinkImpl) findViewLink("ContinvOpportunitiesFkLink1");
    }

    /**
     * Container's getter for opportunityMianContactSubContactViewLink1.
     * @return opportunityMianContactSubContactViewLink1
     */
    public ViewLinkImpl getopportunityMianContactSubContactViewLink1() {
        return (ViewLinkImpl) findViewLink("opportunityMianContactSubContactViewLink1");
    }
    
    public String  incrementBudget(BigDecimal OppId,BigDecimal budget){
       String result ="";
       Row[] rows =  getOpportunitiesVO1().findByKey(new Key(new Object[] { OppId }), 1);
        if (rows != null && rows.length > 0) {
                Row row = rows[0];
                row.setAttribute("BudgetAmount", budget);
                result =
                        "Updated Budget for " + row.getAttribute("OppName") +
                        " " + " to " + budget;
                       
            }
       return result;
    }

}

